# Site Settings
title: Copernicus Component Library
email: Michel.WAKIM@icfnext.com
description: >
  Copernicus Component Library
baseurl: "/copernicus-component-library"
url: "https://eu-copernicus.github.io"
github_username:  eu-copernicus
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM