# Site Settings
title: Copernicus Component Library
email: martin@codex42.be
description: >
  Copernicus Component Library
baseurl: "/copernicus-component-library"
url: "https://eu-copernicus.github.io"
github_username:  codex42
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM